import { clsx } from 'clsx';
import type { Metadata } from 'next';
import './globals.css';
import { Playfair_Display } from 'next/font/google';

const playfairDisplay = Playfair_Display({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-playfair-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(playfairDisplay.variable)}>
      <body className={clsx('min-h-screen')}>
        <header>
          <h1>I AM LOGO</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
